DROP TABLE IF EXISTS restaurant;

CREATE TABLE restaurant (
    id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    origin VARCHAR(100),
    type VARCHAR(100) NOT NULL,
    name VARCHAR(255) NOT NULL,
    image VARCHAR(255),
    description VARCHAR(255),
    price int(10) NOT NULL
);
INSERT INTO restaurant (origin, type, name, price)
VALUES
	("iran", "main", "Kebab with small portion of rice", 40),
	("iran", "main", "Kookoo (vegetables)", 20),
	("iran", "main", "Tahchin", 35),
	("iran", "main", "Mix Kebab with Rice", 45),
	("iran", "main", "Kotlet", 23),
	("iran", "main", "Kashk-e Badenjun", 25),
	("usa", "main", "Steak", 60),
	("usa", "main", "Pasta", 24),
	("usa", "main", "Salmon & Zucchini", 48),
	("usa", "main", "Goetta", 43),
	("usa", "main", "Meatball", 50),
	("usa", "main", "Hamburger & French fries", 54),
	("asia", "main", "Sushi", 42),
	("asia", "main", "Tom Yum", 35),
	("asia", "main", "Satay", 45),
	("asia", "main", "Chinese Udon Noodles", 38),
	("asia", "main", "Spicy Ramen", 30),
	("asia", "main", "Fresh Dim Sum", 23),
	("middle-east", "main", "Chicken Kabsa", 44),
	("middle-east", "main", "Lebanese: Bulgur, tomato, onion", 28),
	("middle-east", "main", "Pilaf with Shrimp", 53),
	("middle-east", "main", "Fish Beryani", 49),
	("middle-east", "main", "Baba Ganoush", 23),
	("middle-east", "main", "Manakeesh", 33),
	("iran", "salad", "Shirazi Salad", 15),
	("iran", "salad", "Mast-o-Khiar", 10),
	("usa", "salad", "American grilled-peach salad", 25),
	("usa", "salad", "Cobb Salad", 20),
	("asia", "salad", "Vietnamese chicken salad with rice", 23),
	("asia", "salad", "Asian Rice Salad With Shrimp", 24),
	("middle-east", "salad", "Tabbouleh Salad", 20),
	("middle-east", "salad", "Fattoush Salad", 18),
	("iran", "dessert", "Faloodeh Shirazi", 8),
	("usa", "dessert", "Apple Pie Ice Cream Pie", 7),
	("asia", "dessert", "Ichigo Daifuku", 12),
	("middle-east", "dessert", "Basbousa", 13),
	(NULL, "beverage", "Pepsi", 3),
	(NULL, "beverage", "Pepsi 1.5L", 6),
	(NULL, "beverage", "Pepsi Coffee", 4),
	(NULL, "beverage", "Coca Cola", 2.5),
	(NULL, "beverage", "Coca Cola 1.5L", 4),
	(NULL, "beverage", "Purified Water", 1.3);